# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spdy}
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roman Shterenzon"]
  s.date = %q{2011-05-25}
  s.default_executable = %q{spdyd}
  s.description = %q{SPDY daemon}
  s.email = %q{romanbsd@yahoo.com}
  s.executables = ["spdyd"]
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    ".gitignore",
    "README",
    "Rakefile",
    "bin/spdyd",
    "examples/access_log",
    "examples/local.ru",
    "ext/base/base_api.h",
    "ext/base/basictypes.h",
    "ext/base/compiler_specific.h",
    "ext/base/logging.h",
    "ext/base/memory/scoped_ptr.h",
    "ext/base/port.h",
    "ext/build/build_config.h",
    "ext/em_setsockopt.c",
    "ext/extconf.rb",
    "ext/module.cc",
    "ext/net/base/net_api.h",
    "ext/net/base/sys_byteorder.h",
    "ext/net/spdy/spdy_bitmasks.h",
    "ext/net/spdy/spdy_frame_builder.cc",
    "ext/net/spdy/spdy_frame_builder.h",
    "ext/net/spdy/spdy_framer.cc",
    "ext/net/spdy/spdy_framer.cc.orig",
    "ext/net/spdy/spdy_framer.h",
    "ext/net/spdy/spdy_framer.h.orig",
    "ext/net/spdy/spdy_protocol.h",
    "lib/rack/handler/spdy.rb",
    "lib/spdy.rb",
    "lib/spdy/backend.rb",
    "lib/spdy/rack_backend.rb",
    "lib/spdy/request.rb",
    "lib/spdy/server.rb",
    "lib/spdy/session.rb",
    "lib/spdy/stream.rb",
    "spdy.gemspec"
  ]
  s.homepage = %q{http://github.com/romanbsd/spdy}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{SPDY daemon}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, ["~> 0.12.10"])
      s.add_runtime_dependency(%q<daemons>, ["~> 1.1.3"])
      s.add_runtime_dependency(%q<em-http-request>, ["~> 0.3.0"])
    else
      s.add_dependency(%q<eventmachine>, ["~> 0.12.10"])
      s.add_dependency(%q<daemons>, ["~> 1.1.3"])
      s.add_dependency(%q<em-http-request>, ["~> 0.3.0"])
    end
  else
    s.add_dependency(%q<eventmachine>, ["~> 0.12.10"])
    s.add_dependency(%q<daemons>, ["~> 1.1.3"])
    s.add_dependency(%q<em-http-request>, ["~> 0.3.0"])
  end
end

